
const data={
    productData:[
        {
            id:1,
            img:"https://www.seekpng.com/png/detail/153-1537893_red-apples-png-maa-com-fundo-branco.png",
            title:'Apple',
            desc:'',
            price:50,
        },
        {
            id:2,
            img:"https://freepngimg.com/thumb/mango/9-2-mango-transparent.png",
            title:'Mango',
            desc:'',
            price:40,
        },
        {
            id:3,
            img:"https://pngimg.com/uploads/orange/orange_PNG791.png",
            title:'Orange',
            desc:'',
            price:45,
        },
        {
            id:4,
            img:"https://cdn.pixabay.com/photo/2016/02/23/17/29/banana-1218133_1280.png",
            title:'Banana',
            desc:'',
            price:60,
        },
        {
            id:5,
            img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdOa_UcXQm9g_m2jNH1P0I9aNvM1kyyR2aXg&usqp=CAU",
            title:'Carrot',
            desc:'',
            price:30,
        },
        {
            id:6,
            img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFln9S6m-jcb_tFsvuqSrqq51_5y-UzpTicw&usqp=CAU",
            title:'Ladies Finger',
            desc:'',
            price:20,
        }, 
        {
            id:7,
            img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFwFmLaQRFDtSH44xZIk6ltGvS43vQRa7u8z9cuBGyHoL2C6W7AbRH6zsYLib7te2Leg4&usqp=CAU",
            title:'Cabbage',
            desc:'',
            price:25,
        },
        {
            id:8,
            img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYvymZ4VQ1p4oSeg5_IYeCjyVL1m2sap8DCoJ2vGPzk2fxnUHpsGX3NYzeABVcXb_VwpM&usqp=CAU",
            title:'Tomato',
            desc:'',
            price:55,
        },
    ]
}
export default data;